apiVersion: th2.exactpro.com/v1
kind: Th2Box
metadata:
  name: act-uiframework-web
spec:
  image-name: ghcr.io/th2-net/th2-act-uiframework-web-demo
  image-version: 3.4.0
  type: th2-act
  custom-config:
    act_url: 'https://cluster-ip:30443/th2-hand-web-154/act-ui/'
  pins:
    - name: server
      connection-type: grpc
    - name: to_check1
      connection-type: grpc
    - name: to_hand
      connection-type: grpc
  extended-settings:
    service:
      enabled: true
      type: NodePort
      endpoints:
        - name: 'grpc'
          targetPort: 8080
          nodePort: "31704"
    envVariables:
      JAVA_TOOL_OPTIONS: "-XX:+ExitOnOutOfMemoryError"
    resources:
      limits:
        memory: 200Mi
        cpu: 200m
      requests:
        memory: 101Mi
        cpu: 50m
        
        
