apiVersion: th2.exactpro.com/v1
kind: Th2Box
metadata:
  name: act-fix
spec:
  image-name: ghcr.io/th2-net/th2-act-template-j
  image-version: 3.4.1
  type: th2-act
  pins:
    # Server
    - name: server
      connection-type: grpc
    # Client
    - name: to_check1
      connection-type: grpc
    - name: to_script
      connection-type: grpc
    - name: from_codec
      connection-type: mq
      attributes:
        - first
        - oe
        - subscribe
        - parsed
    - name: to_send
      connection-type: mq
      attributes:
        - publish
        - parsed
  extended-settings:
    service:
      enabled: true
      type: NodePort
      endpoints:
        - name: 'grpc'
          targetPort: 8080
          nodePort: 31178
    envVariables:
      JAVA_TOOL_OPTIONS: "-XX:+ExitOnOutOfMemoryError"
    resources:
      limits:
        memory: 200Mi
        cpu: 200m
      requests:
        memory: 100Mi
        cpu: 20m