apiVersion: th2.exactpro.com/v1
kind: Th2Box
metadata:
  name: codec-hand
spec:
  image-name: ghcr.io/th2-net/th2-codec-hand
  image-version: 0.1.4
  type: th2-codec
  custom-config:
    contentKey: "ActionResults"
  pins:
    # decoder
    - name: in_codec_decode
      connection-type: mq
      attributes:
        - decoder_in
        - raw
        - subscribe
    - name: out_codec_decode
      connection-type: mq
      attributes:
        - decoder_out
        - parsed
        - publish
        - store
    # decoder general (technical)
    - name: in_codec_general_decode
      connection-type: mq
      attributes:
        - general_decoder_in
        - raw
        - subscribe
    - name: out_codec_general_decode
      connection-type: mq
      attributes:
        - general_decoder_out
        - parsed
        - publish
  extended-settings:
    service:
      enabled: false
    envVariables:
      JAVA_TOOL_OPTIONS: "-XX:+ExitOnOutOfMemoryError"
    resources:
      limits:
        memory: 200Mi
        cpu: 600m
      requests:
        memory: 100Mi
        cpu: 20m

