apiVersion: th2.exactpro.com/v1
kind: Th2Box
metadata:
  name: fix-demo-server2
spec:
  image-name: ghcr.io/th2-net/th2-conn-fix
  image-version: 3.2.1
  type: th2-conn
  custom-config:
    session-alias: fix-demo-server2
    workspace: /home/sailfish/workspace
    type: th2_service:FIX_Server
    name: fix-demo-server2
    settings:
      autoStartable: true
      expectedTimeOfStarting: 2000
      invertStoredMessageTypes: false
      performDump: false
      persistMessages: true
      waitingTimeBeforeStarting: 0
      allowUnknownMsgFields: false
      beginString: FIXT.1.1
      checkLatency: false
      defaultApplVerID: 9
      duplicateTagsAllowed: false
      endTime: 00:00:00
      fileStorePath: store/fix/sessions
      logHeartbeats: true
      maxLatency: 120
      microsecondsInTimeStampFields: false
      millisecondsInTimeStampFields: true
      orderingFields: false
      receiveLimit: 0
      rejectInvalidMessage: false
      resetOnDisconnect: true
      resetOnLogout: true
      senderCompID: FGW
      startTime: 00:00:00
      targetCompID: DEMO-CONN2
      useLocalTime: false
      useSSL: false
      validateFieldsHaveValues: true
      validateFieldsOutOfOrder: true
      validateFieldsOutOfRange: true
      validateSequenceNumbers: false
      validateUserDefinedFields: true
      applicationClassName: com.exactpro.sf.services.fix.ServerApplication
      keepMessagesInMemory: true
      socketAcceptPort: 8080
  pins:
    - name: in_raw
      connection-type: mq
      attributes:
        - first
        - raw
        - publish
    - name: out_raw
      connection-type: mq
      attributes:
        - second
        - raw
        - publish
    - name: fix_to_send
      connection-type: mq
      attributes:
        - send
        - raw
        - subscribe
      filters:
        - metadata:
            - field-name: session_alias
              expected-value: fix-demo-server2
              operation: EQUAL
  extended-settings:
    service:
      enabled: true
      type: NodePort
      endpoints:
        - name: 'other'
          targetPort: 8080
          nodePort: 31681
    envVariables:
      JAVA_TOOL_OPTIONS: "-XX:+ExitOnOutOfMemoryError"
    resources:
      limits:
        memory: 200Mi
        cpu: 200m
      requests:
        memory: 100Mi
        cpu: 20m
