apiVersion: th2.exactpro.com/v1
kind: Th2Box
metadata:
  name: hand
spec:
  image-name: ghcr.io/th2-net/th2-hand
  image-version: 3.8.0
  type: th2-hand
  custom-config:
    session-alias: "th2-hand-demo"
    driversMapping:
      chrome-node-1:
        type: "web"
        url: "http://selenium-chrome:8080"
    rhOptions:
      ReadClipboardAccess: true
      useWebpImageEncoder: true
      WebpLosslessCompression: false
      WebpQualityFactor: 60
  pins:
    - name: send_raw
      connection-type: mq
      attributes:
        - publish
        - raw
        - store
    - name: server
      connection-type: grpc
  extended-settings:
    service:
      enabled: true
      type: NodePort
      endpoints:
        - name: 'grpc'
          targetPort: 8080
    envVariables:
      JAVA_TOOL_OPTIONS: "-XX:+ExitOnOutOfMemoryError"
    resources:
      limits:
        memory: 400Mi
        cpu: 600m
      requests:
        memory: 100Mi
        cpu: 20m
