apiVersion: th2.exactpro.com/v1
kind: Th2Box
metadata:
  name: recon
spec:
  image-name: nexus.exactpro.com:9000/th2-check2-recon-template
  image-version: 2.1.14
  type: th2-check2-recon
  custom-config:
    recon_name: Demo_Recon
    cache_size: 100
    event_batch_max_size: 10
    event_batch_send_interval: 1
    rules_package_path: rules
    rules:
      - name: "demo_conn1_vs_demo_conn2"
        enabled: true
        match_timeout: 300
        match_timeout_offset_ns: 0
        configuration:
          demo-conn1: "ER_FIX01"
          demo-conn2: "ER_FIX02"
      - name: "log_vs_demo_conn"
        enabled: true
        match_timeout: 300
        match_timeout_offset_ns: 0
        configuration:
          demo-conn1: "NOS_CONN"
          demo-conn2: "NOS_CONN"
          demo-log: "NOS_LOG"
  pins:
    - name: incoming 
      connection-type: mq
      attributes:
        - parsed
        - subscribe
    - name: to_util
      connection-type: grpc
  extended-settings:
    service:
      enabled: "false"
    resources:
      limits:
        memory: 200Mi
        cpu: 200m
      requests:
        memory: 100Mi
        cpu: 20m
