apiVersion: th2.exactpro.com/v1
kind: Th2Link
metadata:
  name: from-codec-links
spec:
  boxes-relation:
    router-mq:
    - name: codec-to-act
      from:
        box: codec-fix
        pin: out_codec_decode
      to:
        box: act-fix
        pin: from_codec
    - name: codec-to-check1
      from:
        box: codec-fix
        pin: out_codec_decode
      to:
        box: check1
        pin: from_codec
    - name: codec-to-recon
      from:
        box: codec-fix
        pin: out_codec_decode
      to:
        box: recon
        pin: incoming
    - name: provider-to-codec
      from:
        box: rpt-data-provider
        pin: to_codec
      to:
        box: codec-fix
        pin: in_codec_general_decode
    - name: codec-to-provider
      from:
        box: codec-fix
        pin: out_codec_general_decode
      to:
        box: rpt-data-provider
        pin: from_codec
    - name: codec-sim-to-sim
      from:
        box: codec-sim-fix
        pin: out_codec_decode
      to:
        box: sim-demo
        pin: subscribe
    - name: cradle-viewer-to-codec
      from:
        box: cradle-viewer-entry-point
        pin: to_codec
      to:
        box: codec-sim-fix
        pin: in_codec_general_decode
    - name: codec-to-cradle-viewer
      from:
        box: codec-sim-fix
        pin: out_codec_general_decode
      to:
        box: cradle-viewer-entry-point
        pin: from_codec
