apiVersion: th2.exactpro.com/v1
kind: Th2Link
metadata:
  name: links
spec:
##############################################################################
###                           DICTIONARIES                                 ###
##############################################################################
  dictionaries-relation:
    - name: codec-fix-dictionary
      box: codec-fix
      dictionary:
        name: fix50-generic
        type: MAIN

##############################################################################
    - name: demo-conn1-dictionary
      box: demo-conn1
      dictionary:
        name: fix50-generic
        type: MAIN
##############################################################################
    - name: demo-dc1-dictionary
      box: demo-dc1
      dictionary:
        name: fix50-generic
        type: MAIN
##############################################################################
    - name: codec-sim-dictionary
      box: codec-sim-fix
      dictionary:
        name: fix50-generic
        type: MAIN
##############################################################################
    - name: server1-dictionary
      box: fix-demo-server1
      dictionary:
        name: fix50-generic
        type: MAIN
##############################################################################
    - name: serverdc1-dictionary
      box: dc-demo-server1
      dictionary:
        name: fix50-generic
        type: MAIN
##############################################################################
###                           BOXES MQ                                     ###
##############################################################################
  boxes-relation:
    router-mq:
#####################ACT-UI-BACKEND -> CODEC-FIX##############################
      - name: act-to-fix-codec
        from:
          box: act-ui-backend
          pin: to-fix-codec
        to:
          box: codec-fix
          pin: in_codec_encode
##############################################################################
#####################CODEC-FIX -> CHECK1######################################
      - name: codec-to-check1
        from:
          box: codec-fix
          pin: out_codec_decode
        to:
          box: check1
          pin: from_codec
##############################################################################
#####################CODEC-SIM-FIX -> SIM-DEMO################################
      - name: codec-sim-to-sim
        from:
          box: codec-sim-fix
          pin: out_codec_decode
        to:
          box: sim-demo
          pin: subscribe
##############################################################################
#####################RPT-DATA-PROVIDER -> CODEC-FIX###########################
      - name: provider-to-codec
        from:
          box: rpt-data-provider
          pin: to_codec
        to:
          box: codec-fix
          pin: in_codec_general_decode
##############################################################################
#####################CODEC-FIX -> RPT-DATA-PROVIDER###########################
      - name: codec-to-provider
        from:
          box: codec-fix
          pin: out_codec_general_decode
        to:
          box: rpt-data-provider
          pin: from_codec
##############################################################################
#####################RPT-DATA-PROVIDER -> CODEC-HAND###########################
      - name: provider-to-codec-hand
        from:
          box: rpt-data-provider
          pin: to_codec_hand
        to:
          box: codec-hand
          pin: in_codec_general_decode
##############################################################################
#####################HAND -> CODEC-HAND#######################################
      - name: hand-to-codec-hand
        from:
          box: hand
          pin: send_raw
        to:
          box: codec-hand
          pin: in_codec_decode
##############################################################################
#####################CODEC-HAND -> CODEC-FIX#############################
      - name: codec-hand-to-codec-fix
        from:
          box: codec-hand
          pin: out_codec_general_decode
        to:
          box: codec-fix
          pin: in_codec_general_decode
      - name: codec-hand-to-codec-fix-2
        from:
          box: codec-hand
          pin: out_codec_decode
        to:
          box: codec-fix
          pin: in_codec_decode
##############################################################################
#####################CODEC-FIX -> DEMO-CONN1##################################
      - name: from-codec-to-demo-conn1
        from:
          box: codec-fix
          pin: out_codec_encode
        to:
          box: demo-conn1
          pin: fix_to_send
##############################################################################
#####################DEMO-CONN1(FIRST) -> CODEC-FIX###########################
      - name: democonn1-codec
        from:
          box: demo-conn1
          pin: in_raw
        to:
          box: codec-fix
          pin: in_codec_decode
##############################################################################
#####################DEMO-DC1(FIRST) -> CODEC-FIX#############################
      - name: demodc1-codec
        from:
          box: demo-dc1
          pin: in_raw
        to:
          box: codec-fix
          pin: in_codec_decode
##############################################################################
#####################DEMO-CONN1(SECOND) -> CODEC-FIX##########################
      - name: demo-conn1_out-codec
        from:
          box: demo-conn1
          pin: out_raw
        to:
          box: codec-fix
          pin: in_codec_decode
##############################################################################
#####################DEMO-DC1(SECOND) -> CODEC-FIX############################
      - name: demo-dc1_out-codec
        from:
          box: demo-dc1
          pin: out_raw
        to:
          box: codec-fix
          pin: in_codec_decode
##############################################################################
#####################SIM-DEMO -> CODEC-SIM####################################
      - name: sim-server1
        from:
          box: sim-demo
          pin: send1
        to:
          box: codec-sim-fix
          pin: in_codec_encode
##############################################################################
#####################SIM-DEMO -> CODEC-SIM####################################
      - name: sim-server2
        from:
          box: sim-demo
          pin: send2
        to:
          box: codec-sim-fix
          pin: in_codec_encode
##############################################################################
#####################SIM-DEMO -> CODEC-SIM####################################
      - name: sim-serverdc1
        from:
          box: sim-demo
          pin: send3
        to:
          box: codec-sim-fix
          pin: in_codec_encode
##############################################################################
#####################CODEC-SIM -> FIX-DEMO-SERVER1############################
      - name: codec-fix-server1
        from:
          box: codec-sim-fix
          pin: out_codec_encode
        to:
          box: fix-demo-server1
          pin: fix_to_send
##############################################################################
#####################CODEC-SIM -> DC-DEMO-SERVER1#############################
      - name: codec-dc-server1
        from:
          box: codec-sim-fix
          pin: out_codec_encode
        to:
          box: dc-demo-server1
          pin: fix_to_send
##############################################################################
#####################FIX-DEMO-SERVER1 -> CODEC-SIM############################
      - name: server1-codec
        from:
          box: fix-demo-server1
          pin: in_raw
        to:
          box: codec-sim-fix
          pin: in_codec_decode
##############################################################################
###                         BOXES GRPC                                     ###
##############################################################################
    router-grpc:
##############################################################################
#####################ACT-GUI -> CHECK1########################################
      - name: act-uiframework-web-demo-to-check1
        from:
          service-class: com.exactpro.th2.check1.Check1Handler
          strategy: filter
          box: act-uiframework-web
          pin: to_check1
        to:
          service-class: com.exactpro.th2.check1.grpc.Check1Service
          strategy: robin
          box: check1
          pin: server
##############################################################################
#####################ACT-GUI -> HAND##########################################
      - name: act-uiframework-web-demo-to-hand
        from:
          strategy: filter
          box: act-uiframework-web
          pin: to_hand
        to:
          service-class: com.exactpro.th2.act.grpc.hand.RhBatchService
          strategy: robin
          box: hand
          pin: server
##############################################################################
#####################SCRIPT -> ACT-FIX########################################
      - name: script-to-act
        from:
          service-class: com.exactpro.th2.act.HandWinAct
          strategy: filter
          box: script-entry-point
          pin: to_act
        to:
          service-class: com.exactpro.th2.act.grpc.HandWinActService
          strategy: robin
          box: act-uiframework-web
          pin: server
##############################################################################
#####################SCRIPT -> CHECK1#########################################
      - name: script-to-check1
        from:
          service-class: com.exactpro.th2.check1.Check1Handler
          strategy: filter
          box: script-entry-point
          pin: to_check1
        to:
          service-class: com.exactpro.th2.check1.grpc.Check1Service
          strategy: robin
          box: check1
          pin: server
