apiVersion: th2.exactpro.com/v1
kind: Th2CoreBox
metadata:
  name: rpt-data-viewer
spec:
  image-name: ghcr.io/th2-net/th2-rpt-viewer
  image-version: 2.0.20
  type: th2-rpt-viewer
  extended-settings:
    service:
      enabled: true
      type: NodePort
      endpoints:
        - name: 'other'
          targetPort: 80
          nodePort: 31279
    envVariables:
      JAVA_TOOL_OPTIONS: "-XX:+ExitOnOutOfMemoryError"
    resources:
      limits:
        memory: 300Mi
        cpu: 210m
      requests:
        memory: 50Mi
        cpu: 50m
#      mounitng:
#        TBD
